import React, {Component} from "react";
import ReactDOM from "react-dom";
import {Email, Item, Image, Box, Span, A, renderEmail} from 'react-html-email';

const sourceURL = 'https://raw.githubusercontent.com/chromakode/react-html-email/master/examples/kitchenSink.js'

const css = `
@media only screen and (max-device-width: 480px) {
  font-size: 20px !important;
}`.trim()

class App extends Component {
  constructor() {
    super();
    this.state = {
      value: ""
    };
  }

  render() {
    return (
      <Email title="Test Email" headCSS={css}>
        <Item>
          <Span fontSize={10}>Stop everything! Your weekly update of all things Nicopure is here.</Span>
        </Item>
        <Item>
          <Box cellSpacing={20} width="100%" style={{borderTop: '3px solid black'}}>
            <Item>
              <Span color="gray" lineHeight={20}>Generated by <A href="https://github.com/chromakode/react-html-email">react-html-email</A></Span>
              <Image data-mc-bar="bar" data-mc-baz="baz" alt="react" src="https://halocigs.com/media/media/emails/nicopure-logo-180px.png" width={180} height={94}/>
              <A download={sourceURL} href={sourceURL}>Source code</A>
            </Item>
          </Box>
        </Item>
      </Email>
    );
  }
}

export default App;

ReactDOM.render(<App/>, document.getElementById("root"));